name: lint-and-test
on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3.5.1
        with:
          node-version: '14'
      - run: npm install
      - run: npm run lint
  test:
    strategy:
      matrix:
        os: [windows, macos, ubuntu]
        node: ['10', '12', '14']
    runs-on: ${{ matrix.os }}-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3.5.1
        with:
          node-version: ${{ matrix.node }}
      - run: npm install
      - run: npm test
